### ISSUE TITLE
Crash at inishlizing game

### ISSUE THREAD

**Issue by Hunterghost92** [ThinkingStudios/RyoamicLights#47]
game crashes at initialization---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2024-10-04 09:18:45**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Minecraft [e.g. 1.16.4]
 - Fabric Loader version [e.g. 0.10.6+build.214]
 - Mods [e.g. fabric-api v0.25.1+build.416-1.16, lambdynamiclig**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Minecraft [e.g. 1.16.4]
 - Fabric Loader version [e.g. 0.10.6+build.214]
 - Mods [e.g. fabric-api v0.25.1+build.416-1.16, lambdynamiclights v1.3.2, modmenu v1.14.6+build.31]
 - Version [e.g. 1.3.2]
 - Branch [e.g. mc1.16]

**Additional context**
hts v1.3.2, modmenu v1.14.6+build.31]
 - Version [e.g. 1.3.2]
 - Branch [e.g. mc1.16]

**Additional context**

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ryoamiclights' at 'org.thinkingstudio.ryoamiclights.fabric.RyoamicLightsFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$fbl000$notenoughcrashes$catchFabricInit(class_310.java:28172)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: dev/lambdaurora/lambdynlights/api/DynamicLightHandler
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.thinkingstudio.ryoamiclights.fabric.RyoamicLightsFabric.onInitializeClient(RyoamicLightsFabric.java:34)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 8 more
Caused by: java.lang.ClassNotFoundException: dev.lambdaurora.lambdynlights.api.DynamicLightHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$fbl000$notenoughcrashes$catchFabricInit(class_310.java:28172)
	at net.minecraft.class_310.<init>(class_310.java:477)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 6.8.0-38-generic
	Java Version: 21.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 705997768 bytes (673 MiB) / 1224736768 bytes (1168 MiB) up to 4110417920 bytes (3920 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: 2nd Generation Core Processor Family Integrated Graphics Controller
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x0126
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 7819.92
	Virtual memory used (MiB): 3914.33
	Swap memory total (MiB): 3909.96
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 5961.76, total: 19031.23
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 5961.76, total: 19031.23
	Space in storage for io.netty.native.workdir (MiB): available: 5961.76, total: 19031.23
	Space in storage for java.io.tmpdir (MiB): available: 5961.76, total: 19031.23
	Space in storage for workdir (MiB): available: 5961.76, total: 19031.23
	JVM Flags: 7 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3909m
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.0.5
		antique_atlas: Antique Atlas 2.9.17+1.21
			surveyor: Surveyor Map Framework 0.6.23+1.21
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		astrocraft: Astrocraft 1.4.4+1.21.1
		autotools: AutoTools 2.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc9216a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
		badpackets: Bad Packets 0.8.1
		balm-fabric: Balm 21.0.19
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		bclib: BCLib 21.0.13
		beb: Beautiful Enchanted Books 1.0.0
		betterend: Better End 21.0.11
		betterf3: BetterF3 11.0.2
		betternether: Better Nether 21.0.11
		betterstats: Better Statistics Screen 3.13.2+fabric-1.21
		betterthanmending: BetterThanMending 2.1.0
		betterthirdperson: Better Third Person 1.9.0
		bigglobe: Big Globe 4.3.3
			builderb0y_autocodec: autocodec 4.12.1
		bobby: Bobby 5.2.4+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bridgingmod: Bridging Mod 2.4.0+1.21
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.212+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.212+1.21.1
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.212+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.212+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.212+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.212+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.212+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.212+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.212+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.212+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.212+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.212+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.212+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.212+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.212+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.212+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.212+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.212+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.212+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.212+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			mixinsquared: MixinSquared 0.2.0-beta.6
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		camerautils: Camera Utils 1.21.1-1.0.16
		chunky: Chunky 1.4.16
		cicada: CICADA 0.8.3+1.21-and-above
		citresewn: CIT Resewn 1.2.1+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.1+1.21
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		configured: Configured 1.3.1
			betterconfig: BetterConfig 1.3
		continuity: Continuity 3.0.0-beta.5+1.21
		coroutil: CoroUtil 1.21.0-1.3.7
		craftingtweaks: Crafting Tweaks 21.1.2
		crawl: Crawl 0.13.0
		creativecore: CreativeCore 2.12.9
			net_neoforged_bus: bus 7.2.0
		cristellib: Cristel Lib 1.2.8
		do_a_barrel_roll: Do a Barrel Roll 3.6.2+1.21
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		doubledoors: Double Doors 5.9
		dungeons_arise: When Dungeons Arise 2.1.60
		durabilitytooltip: Durability Tooltip 1.1.5
		dynamic_fps: Dynamic FPS 3.7.3
			net_lostluma_battery: battery 1.1.0
		e4mc_minecraft: e4mc 5.2.1
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.1
		eatinganimationid: Eating Animation 1.21+1.9.72
		effecttimerplus: EffectTimerPlus 2.2.2
		effortless: Effortless Structure 3.1.0
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Minecraft [e.g. 1.16.4]
 - Fabric Loader version [e.g. 0.10.6+build.214]
 - Mods [e.g. fabric-api v0.25.1+build.416-1.16, lambdynamiclights v1.3.2, modmenu v1.14.6+build.31]
 - Version [e.g. 1.3.2]
 - Branch [e.g. mc1.16]

**Additional context**

			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.2+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.2
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.2
		fallingtrees: Panda's Falling Tree's 0.12.7
		fastquit: FastQuit 3.0.0+1.20.6
		ferritecore: FerriteCore 7.0.0
		firstperson: FirstPerson 2.4.5
		freecam: Freecam (Modrinth Edition) 1.3.0+mc1.21
		gammautils: Gamma Utils 2.1.0
		hardcorerevival: Hardcore Revival 21.1.2
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		immersiveui: ImmersiveUI 0.2.2
		inventory_tabs: Inventory Tabs 1.4.0+1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.4
		invmove: InvMove 0.8.8
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jamlib: JamLib 1.0.11+1.21
			blue_endless_jankson: jankson 1.2.3
		java: Java HotSpot(TM) 64-Bit Server VM 21
		jei: Just Enough Items 19.18.10.218
		journeymap: Journeymap 1.21-6.0.0-beta.25
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.16-1.21
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21-SNAPSHOT
		journeymap_webmap: JourneyMap WebMap 1.0.1
			info_journeymap_webmap-client: webmap-client 1.1-SNAPSHOT
			io_javalin_javalin: javalin 6.1.6
			jakarta_servlet_jakarta_servlet-api: jakarta.servlet-api 6.1.0
			org_eclipse_jetty_jetty-http: jetty-http 11.0.20
			org_eclipse_jetty_jetty-io: jetty-io 11.0.20
			org_eclipse_jetty_jetty-security: jetty-security 11.0.20
			org_eclipse_jetty_jetty-server: jetty-server 11.0.20
			org_eclipse_jetty_jetty-servlet: jetty-servlet 11.0.20
			org_eclipse_jetty_jetty-util: jetty-util 11.0.20
			org_eclipse_jetty_jetty-webapp: jetty-webapp 11.0.20
			org_eclipse_jetty_jetty-xml: jetty-xml 11.0.20
			org_eclipse_jetty_toolchain_jetty-jakarta-servlet-api: jetty-jakarta-servlet-api 5.0.2
		kleeslabs: KleeSlabs 21.0.2
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		libipn: libIPN 6.0.2
		litematica: Litematica 0.19.50
		litematica-printer: Litematica Printer 3.5.0-sakura.4
		lithium: Lithium 0.13.1
		lootr: Lootr 1.21-1.10.33.82
		malilib: MaLiLib 0.21.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		minecraft: Minecraft 1.21
		mod-loading-screen: Mod Loading Screen 1.0.4
			com_formdev_flatlaf: flatlaf 3.0
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.2
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		morechathistory: More Chat History 1.3.1
		mousetweaks: Mouse Tweaks 2.26
		mr_dungeons_andtaverns: Dungeons and Taverns 4.4
		mr_hybrid_beta: Cascades (Hybrid Beta) 1.0.4
		mr_lukis_grandcapitals: Luki's Grand Capitals 1.0
		mr_netherweather: Nether Weather 1.1.1
		mru: Mineblock's Repeated Utilities 1.0.2+1.21+fabric
		mvs: Moog's Voyager Structures 4.1.3-1.21-fabric
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		notenoughcrashes: Not Enough Crashes 4.4.8+1.21
		nullscape: Nullscape 1.2.7
		nyfsspiders: Nyf's Spiders 2.3.1
		obsidianui: ObsidianUI 0.2.7+mc1.21
		octolib: OctoLib 0.4.2
			org_yaml_snakeyaml: snakeyaml 2.2
		owo: oωo 0.12.14+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		pandalib: PandaLib 0.4.2
		particular: Particular 1.1.1+1.21
		physicsmod: Physics Mod 3.0.20
		polytone: Polytone 1.21-2.4.16
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		profundis: Profundis 1.7.1
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.4+mc1.21.1
		replaymod: Replay Mod 1.21-2.6.19
		rightclickharvest: Right Click Harvest 4.3.1+1.21
		rrls: Remove Reloading Screen 5.0.7+mc1.21-fabric
		ryoamiclights: RyoamicLights 0.2.9+mc1.21
		saplanting: Saplanting 1.2.6
		satin: Satin 2.0.0
		scalablelux: ScalableLux 0.1.0+fabric.26c6e72
		showmeyourskin: Show Me Your Skin! 1.11.3+1.21
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21
		simple-armor-hud: Simple armor hud 1.21-1.4.5
		skinlayers3d: 3d-Skin-Layers 1.6.7
		smallships: Small Ships 2.0.0-b1.5
			forgeconfigapiport: Forge Config API Port 21.0.8
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		sparsestructures: SparseStructures 2.2.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		swingthrough: SwingThrough 1.0.5+1.21
		t_and_t: Towns and Towers 1.13.2
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21
		team_capes: Team Capes 1.1.1+1.21
		trade_cycling: Trade Cycling 1.21.1-1.0.14
		underground_villages: Underground Villages Mod 4.0.0
		visuality: Visuality 0.7.7+1.21
		voicechat: Simple Voice Chat 1.21.1-2.5.22
		wakes: Wakes 0.3.0+1.21.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
		watut: What Are They Up To 1.21.0-1.1.3
		wi_zoom: WI Zoom 1.5-MC1.21
		worldedit: WorldEdit 7.3.6+6892-3d660b8
		wover: WorldWeaver 21.0.13
			wover-biome: WorldWeaver - Biome API 21.0.13
			wover-block: WorldWeaver - Block and Item API 21.0.13
			wover-common: WorldWeaver - Common API 21.0.13
			wover-core: WorldWeaver - Core API 21.0.13
			wover-datagen: WorldWeaver - Datagen API 21.0.13
			wover-events: WorldWeaver - Events API 21.0.13
			wover-feature: WorldWeaver - Feature API 21.0.13
			wover-generator: WorldWeaver - World Generator API 21.0.13
			wover-item: WorldWeaver - Item API 21.0.13
			wover-math: WorldWeaver - Math API 21.0.13
			wover-preset: WorldWeaver - World Preset API 21.0.13
			wover-recipe: WorldWeaver - Recipe API 21.0.13
			wover-structure: WorldWeaver - Structure API 21.0.13
			wover-surface: WorldWeaver - Surface API 21.0.13
			wover-tag: WorldWeaver - Tag API 21.0.13
			wover-ui: WorldWeaver - UI API 21.0.13
			wunderlib: WunderLib 21.0.8
		wthit: wthit 12.4.2
		xaeroworldmap: Xaero's World Map 1.39.0
	Launched Version: fabric-loader-0.16.5-1.21
	Launcher name: java-minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), RyoamicLights (ryoamiclights), Not Enough Crashes (notenoughcrashes)

**Comment by Greyln** [comment]
+bump
